### ISSUE TITLE
User Story: Sign up

### ISSUE THREAD

**Issue by AyishaSandiford** [AyishaSandiford/treasure-your-recipe-pp4#1]
As a **new user** I can **sign up using my email, username and password** so that **I can create a personal account and start managing my recipes.**

---

### Acceptance Criteria 

- The user can sign up using their email, username and password.

- Error messages appear if required fields are left blank or invalid data is provided.

---

### Task

- [x]  Create the sign-up form UI
- [x]  Implement input validation for email, password, and other fields
- [x]  Set up API to create a new user account
- [x]  Redirect users to the dashboard upon successful sign-up
- [x]   Show error messages when required fields are left blank or invalid data is provided

**Comment by AyishaSandiford** [comment]
Created the sign up form using allauth application

**Comment by AyishaSandiford** [comment]
Completed using allauth application.

**Comment by AyishaSandiford** [comment]
Redirect users to the dashboard upon successful sign-up completed
