### ISSUE TITLE
User Story: Profile Management

### ISSUE THREAD

**Issue by AyishaSandiford** [AyishaSandiford/treasure-your-recipe-pp4#10]
As a **user** I can **update my profile details, such as my name and profile picture** so that **I can keep my account information current.**

---

### Acceptance Criteria 

- The user can update their profile information (name, and profile picture).

- Changes are saved and reflected immediately in the profile view.

- The user receives a success message when profile details are updated.

---

### Task

- [ ]  Design a profile page with fields for name and profile picture.
- [ ]  Implement the ability to update profile fields.
- [ ]  Set up API to save profile changes to the database.
- [ ]  Handle success/error messages after profile updates.
