### ISSUE TITLE
User Story: AutoSave Draft recipe

### ISSUE THREAD

**Issue by AyishaSandiford** [AyishaSandiford/treasure-your-recipe-pp4#11]
As a **user** I want **my recipe drafts to be autosaved as I input data** so that **I don’t lose progress if I accidentally navigate away or close the app.**

---

### Acceptance Criteria 

- The app automatically saves draft recipes as the user enters information.

- The user is informed that their progress has been saved.

- The user can close the app or navigate away without losing their progress.

---

### Task

- [ ]   Implement autosave functionality while editing or creating a recipe.
- [ ]  Store draft data temporarily on the client side.
- [ ]  Set up API to save drafts on the server at regular intervals.
- [ ]  Inform the user when a draft is autosaved.
