### ISSUE TITLE
User Story: View All User Recipes 

### ISSUE THREAD

**Issue by AyishaSandiford** [AyishaSandiford/treasure-your-recipe-pp4#12]
As a **user** I can **see a list of all my recipes** so that **I can easily manage and view them.**

---

### Acceptance Criteria 

- The user should see a list of all recipes they have created.

- Each recipe in the list should show the title.

---

### Task

- [x]  Create the "Recipes List" page UI.
- [x]  Fetch all recipes from the database.
- [x]  Display each recipe’s title in a list format.

**Comment by AyishaSandiford** [comment]
User Story: View All User Recipes  completed
