### ISSUE TITLE
User Story: Delete a Recipe

### ISSUE THREAD

**Issue by AyishaSandiford** [AyishaSandiford/treasure-your-recipe-pp4#7]
As a **user** I can **delete recipes I no longer need** so that **I can remove unwanted recipes**

---

### Acceptance Criteria 

- The user can select a recipe to delete.

- A confirmation dialogue appears before the recipe is deleted.

- Upon confirmation, the recipe is removed from the recipe list.

- The user receives a success message upon deletion.

---

### Task

- [ ] Implement a delete button for each recipe.
- [ ] Implement a confirmation dialogue before the deletion.
- [ ] Set up API to delete the recipe from the database.
- [ ] Handle the deletion process and show success/failure messages.
- [ ] Remove the deleted recipe from the list without reloading the page.
