### ISSUE TITLE
User Story: Search Functionality

### ISSUE THREAD

**Issue by AyishaSandiford** [AyishaSandiford/treasure-your-recipe-pp4#8]
As a **role** I can **search for recipes by title** so that **I can quickly find a specific recipe without manually browsing.**

---

### Acceptance Criteria 

- The user can search for recipes by title.

- The search results update instantly based on the entered search terms.

- Acceptance criteria 3

---

### Task

- [ ]  Design a search bar 
- [ ]  Implement search functionality for recipe titles
- [ ]  Set up API to fetch search results based on user input.
- [ ]  Display search results in real-time or upon submission.
